### ISSUE TITLE
analytics.* breaks Twitter URLs

### ISSUE THREAD

**Issue by SanderGit** [mmotti/mmotti-host-file#1]
the analytics.* entry breaks links on Twitter. They cannot be followed because they go through analytics.twitter.com.
Adding analytics.twitter.com to a manual whitelist does not work, because the entry must match the original entry i.e. analytics.*

**Comment by mmotti** [comment]
Will investigate.

The analytics.twitter.com should work for the whitelist, though. Providing you are using SABS.

**Comment by SanderGit** [comment]
Yes, SABS 0.0.9. SABS doesn't enable when adding analytics.twitter.com to the whitelist.

**Comment by mmotti** [comment]
That's odd.

It works for me on the most recent commit - Both adding straight away and
adding, disabling adblocking and re enabling.

**Comment by SanderGit** [comment]
Then it must be a local issue. Anyway feel free to investigate what to do with this entry and close the issue when appropriate.

**Comment by mmotti** [comment]
Let's hope so!

I'll close this issue for now but if we start to see more issues with certain wildcards, I can always remove them and add the domains back.

I will add a whitelist recommendation for analytics.twitter.com in the ReadMe.

Thanks for reporting!
