### ISSUE TITLE
Can not login Binance

### ISSUE THREAD

**Issue by nmhung1985** [mmotti/mmotti-host-file#14]
Hi, I'm using Adhell3 which uses your host file. Currently, if your host file is enabled, I can not login Binance.com (a crypto exchange):
- in their native app, the puzzle captcha would not show up
- in Firefox, the Login button works, but the site would give out errors (as they could not show the captcha i guess)
- in Chrome, even the Login button would not work

Obviously, if the host file is disabled, everything works normally.

Hope you would take a look at this. Thanks.

**Comment by mmotti** [comment]
Hi,

I seem to be able to login with the app and Chrome. Not tried Firefox yet.

Are you using any other host sources? When did you last update host sources
and re-apply blocking?

Size as of today should be 7687 hosts.

**Comment by nmhung1985** [comment]
Hi,

Well, I didn't notice about updating as I thought adhell3 would automatically update the host file (like Adblock or uBlock) but it turned out it didn't :)

I've just "pulled to update" the file and everything is ok now.

Thank you so much. Now I think I'll go to Adhell3 repository to suggest the "updating the host file automatically" feature ;)
