### ISSUE TITLE
*here.com blocks a lot of legit websites

### ISSUE THREAD

**Issue by neFAST** [mmotti/mmotti-host-file#18]
Like pythonanywhere.com
I believe that your recent move from *.something.com to *something.com generates a lot of false positive!

**Comment by mmotti** [comment]
Fixed in https://github.com/mmotti/mmotti-host-file/commit/05b36bfe231cc4e00d5d6c462dabb87db1b4e398

Offending host file: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
