### ISSUE TITLE
Phonearena

### ISSUE THREAD

**Issue by motfis** [mmotti/mmotti-host-file#3]
Hi, you block phonearena.com in the latest list.

**Comment by mmotti** [comment]
Thanks for reporting.

This seems to be an issue with the processing of the adguard filter list. I'll look ASAP for a solution.

**Comment by mmotti** [comment]
@motfis This is now fixed in the most recent commit.

It would seem that the disconnect ad filter (https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt) added phonearena.com.

I have added to the whitelist until it's removed from their list.
