### ISSUE TITLE
Can't load some Google amp webpages

### ISSUE THREAD

**Issue by alionti998** [mmotti/mmotti-host-file#4]
cdn.ampproject.org in host file breaks some amp pages. Tried with CNN and page failed to load via Feedly news ready app in chrome custom tabs. Whitelisting cdn.ampproject.org solves it.

**Comment by mmotti** [comment]
Thanks for reporting! I have removed it in the most recent commit.

It was listed in: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
