### ISSUE TITLE
Please remove *baidu.com from the host.

### ISSUE THREAD

**Issue by herexf** [mmotti/mmotti-host-file#5]
This is a common domain in China which provides music, drive, searching service.

Below 2 domains can be used for most ads.
pos.baidu.com
cpro.baidu.com

Thanks

**Comment by herexf** [comment]
I have submitted same request on SAXX project regarding this issue.

Thanks

**Comment by mmotti** [comment]
I have removed the wildcard.

The only things blocked now should be those supplied by external sources, with the exception of the baiducdn wildcard as my script replaces www. with *

Are you able to access what you need to or do I need to look at this further?

Cheers

**Comment by herexf** [comment]
Thanks, it works now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
