### ISSUE TITLE
Please remove test.com from host

### ISSUE THREAD

**Issue by david082321** [mmotti/mmotti-host-file#6]
this host in your host file : 
> test.com

it will also block this : 
> geetest.com

[https://github.com/JellyBool/geeCaptcha](https://github.com/JellyBool/geeCaptcha)
i can't see this captcha to login.

please remove it.

**Comment by mmotti** [comment]
Will look at this shortly.

It's a shame we have to prefix at the moment as we are going to have more
and more issues like this.

**Comment by mmotti** [comment]
Issue fixed in https://github.com/mmotti/mmotti-host-file/commit/d3954d105363453d6bc7b5f373df301954974d9f
